/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author Naufal K D
 */
public class BiodataSiswa extends javax.swing.JFrame {

    /**
     * Creates new form BiodataSiswa
     */
    public BiodataSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        Combo = new javax.swing.JComboBox<>();
        rbtTKJ = new javax.swing.JRadioButton();
        rbtRPL = new javax.swing.JRadioButton();
        Nama = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Engravers MT", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIODATA SISWA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 30, 270, 30);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 14)); // NOI18N
        jLabel2.setText("ALAMAT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 260, 80, 30);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 14)); // NOI18N
        jLabel3.setText("NAMA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 80, 30);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 14)); // NOI18N
        jLabel4.setText("ABSEN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 80, 30);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 14)); // NOI18N
        jLabel5.setText("KELAS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 180, 80, 30);

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 14)); // NOI18N
        jLabel6.setText("JURUSAN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 220, 80, 30);

        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        getContentPane().add(Alamat);
        Alamat.setBounds(120, 260, 340, 30);
        getContentPane().add(Absen);
        Absen.setBounds(120, 140, 130, 30);

        Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XRPL 1", "XRPL 2", "XRPL 3", "XRPL 4", "XRPL 5", "XRPL 6", "XRPL 7", "XTKJ 1", "XTKJ 2", "XTKJ 3", "XTKJ 4", "XTKJ 5", "XTKJ 6" }));
        getContentPane().add(Combo);
        Combo.setBounds(120, 184, 120, 30);

        btg.add(rbtTKJ);
        rbtTKJ.setText("TKJ");
        getContentPane().add(rbtTKJ);
        rbtTKJ.setBounds(290, 220, 80, 40);

        btg.add(rbtRPL);
        rbtRPL.setText("RPL");
        getContentPane().add(rbtRPL);
        rbtRPL.setBounds(120, 220, 90, 40);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(120, 100, 340, 30);

        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(525, 190, 100, 25);

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(523, 150, 120, 25);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-30, 290, 830, 260);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(-20, -10, 820, 120);

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(-20, 110, 820, 180);

        setBounds(0, 0, 792, 536);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String nm, abs, jur, almt;
        String kelas = Combo.getSelectedItem().toString();
        nm = Nama.getText();
        abs = Absen.getText();
        almt = Alamat.getText();
        //jurusan
        if(rbtRPL.isSelected()){
            jur = "RPL";
            if(Combo.getSelectedItem()== "X RPL 1"){
            }
             if(Combo.getSelectedItem()== "X RPL 2"){
             }
              if(Combo.getSelectedItem()== "X RPL 3"){
              }
               if(Combo.getSelectedItem()== "X RPL 4"){
               }
                if(Combo.getSelectedItem()== "X RPL 5"){
                }
                 if(Combo.getSelectedItem()== "X RPL 6"){
                 }
                  if(Combo.getSelectedItem()== "X RPL 7"){
                  }
        }else if(rbtTKJ.isSelected()){
            jur = "TKJ";
            if(Combo.getSelectedItem()== "X TKJ 1"){
            }
            if(Combo.getSelectedItem()== "X TKJ 2"){
            }
            if(Combo.getSelectedItem()== "X TKJ 3"){
            }
            if(Combo.getSelectedItem()== "X TKJ 4"){
            }
            if(Combo.getSelectedItem()== "X TKJ 5"){
            }
            if(Combo.getSelectedItem()== "X TKJ 6"){
            }
        }else{jur = "";}
        new hasilBiodata(nm,abs,jur,almt,kelas).setVisible(true);
    }//GEN-LAST:event_SubmitActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Alamat;
    private javax.swing.JComboBox<String> Combo;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton Submit;
    private javax.swing.ButtonGroup btg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbtRPL;
    private javax.swing.JRadioButton rbtTKJ;
    // End of variables declaration//GEN-END:variables
}
