/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author Naufal K D
 */
public class Calculator extends javax.swing.JFrame {

    String angka;
    int pilih;
    double angka1,angka2,jumlah;
    
    public Calculator() {
        initComponents();
        angka="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enam = new javax.swing.JButton();
        Empat = new javax.swing.JButton();
        Lima = new javax.swing.JButton();
        Dua = new javax.swing.JButton();
        Tiga = new javax.swing.JButton();
        Sembilan = new javax.swing.JButton();
        Tujuh = new javax.swing.JButton();
        Delapan = new javax.swing.JButton();
        Koma = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Persen = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        btnJumlah = new javax.swing.JButton();
        Nol = new javax.swing.JButton();
        btnsd = new javax.swing.JButton();
        btnPositifNegatif = new javax.swing.JButton();
        btnAkar = new javax.swing.JButton();
        btnkuadrat = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Satu = new javax.swing.JButton();
        C = new javax.swing.JButton();
        btnKurang1 = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KALKULATOR");
        setResizable(false);
        getContentPane().setLayout(null);

        Enam.setText("6");
        Enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnamActionPerformed(evt);
            }
        });
        getContentPane().add(Enam);
        Enam.setBounds(170, 220, 60, 50);

        Empat.setText("4");
        Empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpatActionPerformed(evt);
            }
        });
        getContentPane().add(Empat);
        Empat.setBounds(30, 220, 60, 50);

        Lima.setText("5");
        Lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimaActionPerformed(evt);
            }
        });
        getContentPane().add(Lima);
        Lima.setBounds(100, 220, 60, 50);

        Dua.setText("2");
        Dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuaActionPerformed(evt);
            }
        });
        getContentPane().add(Dua);
        Dua.setBounds(100, 160, 60, 50);

        Tiga.setText("3");
        Tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TigaActionPerformed(evt);
            }
        });
        getContentPane().add(Tiga);
        Tiga.setBounds(170, 160, 60, 50);

        Sembilan.setText("9");
        Sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SembilanActionPerformed(evt);
            }
        });
        getContentPane().add(Sembilan);
        Sembilan.setBounds(170, 280, 60, 50);

        Tujuh.setText("7");
        Tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuhActionPerformed(evt);
            }
        });
        getContentPane().add(Tujuh);
        Tujuh.setBounds(30, 280, 60, 50);

        Delapan.setText("8");
        Delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelapanActionPerformed(evt);
            }
        });
        getContentPane().add(Delapan);
        Delapan.setBounds(100, 280, 60, 50);

        Koma.setText(".");
        Koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KomaActionPerformed(evt);
            }
        });
        getContentPane().add(Koma);
        Koma.setBounds(170, 350, 60, 50);

        Hapus.setText("Backspace");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(210, 410, 160, 50);

        Persen.setText("%");
        Persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersenActionPerformed(evt);
            }
        });
        getContentPane().add(Persen);
        Persen.setBounds(310, 350, 60, 50);

        btnKali.setText("x");
        btnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKali);
        btnKali.setBounds(260, 160, 80, 50);

        btnBagi.setText("/");
        btnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagiActionPerformed(evt);
            }
        });
        getContentPane().add(btnBagi);
        btnBagi.setBounds(260, 220, 80, 50);

        btnJumlah.setText("+");
        btnJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(btnJumlah);
        btnJumlah.setBounds(260, 280, 80, 50);

        Nol.setText("0");
        Nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NolActionPerformed(evt);
            }
        });
        getContentPane().add(Nol);
        Nol.setBounds(30, 350, 130, 50);

        btnsd.setText("=");
        btnsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsdActionPerformed(evt);
            }
        });
        getContentPane().add(btnsd);
        btnsd.setBounds(380, 350, 60, 110);

        btnPositifNegatif.setText("+/-");
        btnPositifNegatif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPositifNegatifActionPerformed(evt);
            }
        });
        getContentPane().add(btnPositifNegatif);
        btnPositifNegatif.setBounds(360, 220, 80, 50);

        btnAkar.setText("√ ");
        btnAkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAkar);
        btnAkar.setBounds(360, 160, 80, 50);

        btnkuadrat.setText("x^2");
        btnkuadrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkuadratActionPerformed(evt);
            }
        });
        getContentPane().add(btnkuadrat);
        btnkuadrat.setBounds(360, 280, 80, 50);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 60, 410, 90);

        Satu.setText("1");
        Satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatuActionPerformed(evt);
            }
        });
        getContentPane().add(Satu);
        Satu.setBounds(30, 160, 60, 50);

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        getContentPane().add(C);
        C.setBounds(30, 410, 170, 50);

        btnKurang1.setText("-");
        btnKurang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurang1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnKurang1);
        btnKurang1.setBounds(240, 350, 60, 50);

        Close.setText("CLOSE");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close);
        Close.setBounds(30, 480, 410, 50);

        jPanel1.setBackground(new java.awt.Color(51, 0, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 250, 350);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(240, -10, 250, 350);

        jPanel3.setBackground(new java.awt.Color(51, 255, 204));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(-10, 340, 480, 210);

        setSize(new java.awt.Dimension(483, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuActionPerformed
        // TODO add your handling code here:
        angka +="1";
        jTextField1.setText(angka);
    }//GEN-LAST:event_SatuActionPerformed

    private void DuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuaActionPerformed
        // TODO add your handling code here:
        angka +="2";
        jTextField1.setText(angka);
    }//GEN-LAST:event_DuaActionPerformed

    private void TigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TigaActionPerformed
        // TODO add your handling code here:
        angka +="3";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TigaActionPerformed

    private void EmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpatActionPerformed
        // TODO add your handling code here:
        angka +="4";
        jTextField1.setText(angka);
    }//GEN-LAST:event_EmpatActionPerformed

    private void LimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimaActionPerformed
        // TODO add your handling code here:
        angka +="5";
        jTextField1.setText(angka);
    }//GEN-LAST:event_LimaActionPerformed

    private void EnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnamActionPerformed
        // TODO add your handling code here:
        angka +="6";
        jTextField1.setText(angka);
    }//GEN-LAST:event_EnamActionPerformed

    private void TujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuhActionPerformed
        // TODO add your handling code here:
        angka +="7";
        jTextField1.setText(angka);
    }//GEN-LAST:event_TujuhActionPerformed

    private void DelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelapanActionPerformed
        // TODO add your handling code here:
        angka +="8";
        jTextField1.setText(angka);
    }//GEN-LAST:event_DelapanActionPerformed

    private void SembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SembilanActionPerformed
        // TODO add your handling code here:
        angka +="9";
        jTextField1.setText(angka);
    }//GEN-LAST:event_SembilanActionPerformed

    private void NolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NolActionPerformed
        // TODO add your handling code here:
        angka +="0";
        jTextField1.setText(angka);
    }//GEN-LAST:event_NolActionPerformed

    private void KomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KomaActionPerformed
        // TODO add your handling code here:
        angka+=".";
        jTextField1.setText(angka);
    }//GEN-LAST:event_KomaActionPerformed

    private void btnsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsdActionPerformed
        // TODO add your handling code here:
        switch (pilih){
            case 1:
                angka2=Double.parseDouble(angka);
                jumlah=angka1+angka2;
                angka=Double.toString(jumlah);
                jTextField1.setText(angka);
                break;
            case 2:
                angka2=Double.parseDouble(angka);
                jumlah=angka1-angka2;
                angka=Double.toString(jumlah);
                jTextField1.setText(angka);
                break;
            case 3:
                angka2=Double.parseDouble(angka);
                jumlah=angka1*angka2;
                angka=Double.toString(jumlah);
                jTextField1.setText(angka);
                break;
            case 4:
                angka2=Double.parseDouble(angka);
                jumlah=angka1/angka2;
                angka=Double.toString(jumlah);
                jTextField1.setText(angka);
                break;
            case 5:
                jumlah = Math.sqrt(angka1);
                angka = Double.toString(jumlah);
                jTextField1.setText(angka);
                break;
            case 6:
                jumlah = angka1 / 100;
                angka = Double.toString(jumlah);
                jTextField1.setText(angka);
                break;
            case 8:
                jumlah = Math.pow(angka1, 2);
                angka = Double.toString(jumlah);
                jTextField1.setText(angka);
                break;
                default:
                break;
        }
    }//GEN-LAST:event_btnsdActionPerformed

    private void btnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        jTextField1.setText("*");
        angka="";
        pilih=3;
    }//GEN-LAST:event_btnKaliActionPerformed

    private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        jTextField1.setText("/");
        angka="";
        pilih=4;
    }//GEN-LAST:event_btnBagiActionPerformed

    private void btnJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJumlahActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        jTextField1.setText("+");
        angka="";
        pilih=1;
    }//GEN-LAST:event_btnJumlahActionPerformed

    private void btnAkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkarActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        jTextField1.setText("√");
        angka="";
        pilih=5;
    }//GEN-LAST:event_btnAkarActionPerformed

    private void btnkuadratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkuadratActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        jTextField1.setText("^");
        angka="";
        pilih=8;
    }//GEN-LAST:event_btnkuadratActionPerformed

    private void btnKurang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurang1ActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        jTextField1.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_btnKurang1ActionPerformed

    private void PersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersenActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        jTextField1.setText("%");
        angka="";
        pilih=6;
    }//GEN-LAST:event_PersenActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka="";
    }//GEN-LAST:event_CActionPerformed

    private void btnPositifNegatifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPositifNegatifActionPerformed
        // TODO add your handling code here:
        if(!angka.contains("-"))
            angka = "-"+angka;
        else
            angka = angka.substring(1, angka.length());
        jTextField1.setText(angka);
    }//GEN-LAST:event_btnPositifNegatifActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        angka = angka.substring(0, angka.length()-1);
        jTextField1.setText(angka);
    }//GEN-LAST:event_HapusActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C;
    private javax.swing.JButton Close;
    private javax.swing.JButton Delapan;
    private javax.swing.JButton Dua;
    private javax.swing.JButton Empat;
    private javax.swing.JButton Enam;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Koma;
    private javax.swing.JButton Lima;
    private javax.swing.JButton Nol;
    private javax.swing.JButton Persen;
    private javax.swing.JButton Satu;
    private javax.swing.JButton Sembilan;
    private javax.swing.JButton Tiga;
    private javax.swing.JButton Tujuh;
    private javax.swing.JButton btnAkar;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnJumlah;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKurang1;
    private javax.swing.JButton btnPositifNegatif;
    private javax.swing.JButton btnkuadrat;
    private javax.swing.JButton btnsd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
