/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

import javax.swing.JTextField;
public class KalkulatorStandart extends javax.swing.JFrame {
    String angka;
    int pilih;
    double angka1,angka2,jumlah;
    
    public KalkulatorStandart() {
        initComponents();
        angka="";
    }
    void angka1(){
        angka +="1";
        btnTampil.setText(angka);
    }
    void angka2(){
        angka +="2";
        btnTampil.setText(angka);
    }
    void angka3(){
        angka +="3";
        btnTampil.setText(angka);
    }
    void angka4(){
        angka +="4";
        btnTampil.setText(angka);
    }
    void angka5(){
        angka +="5";
        btnTampil.setText(angka);
    }
    void angka6(){
        angka +="6";
        btnTampil.setText(angka);
    }
    void angka7(){
        angka +="7";
        btnTampil.setText(angka);
    }
    void angka8(){
        angka +="8";
        btnTampil.setText(angka);
    }
    void angka9(){
        angka +="9";
        btnTampil.setText(angka);
    }
    void angka0(){
        angka +="0";
        btnTampil.setText(angka);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTampil = new javax.swing.JTextField();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnttk = new javax.swing.JButton();
        btnClr = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        btnJumlah = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnsd = new javax.swing.JButton();
        btnPositifNegatif = new javax.swing.JButton();
        btnAkar = new javax.swing.JButton();
        btnkuadrat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(btnTampil);
        btnTampil.setBounds(30, 20, 410, 80);

        btn6.setText("6");
        getContentPane().add(btn6);
        btn6.setBounds(170, 190, 60, 50);

        btn4.setText("4");
        getContentPane().add(btn4);
        btn4.setBounds(30, 190, 60, 50);

        btn5.setText("5");
        getContentPane().add(btn5);
        btn5.setBounds(100, 190, 60, 50);

        btn1.setText("1");
        getContentPane().add(btn1);
        btn1.setBounds(30, 130, 60, 50);

        btn2.setText("2");
        getContentPane().add(btn2);
        btn2.setBounds(100, 130, 60, 50);

        btn3.setText("3");
        getContentPane().add(btn3);
        btn3.setBounds(170, 130, 60, 50);

        btn9.setText("9");
        getContentPane().add(btn9);
        btn9.setBounds(170, 250, 60, 50);

        btn7.setText("7");
        getContentPane().add(btn7);
        btn7.setBounds(30, 250, 60, 50);

        btn8.setText("8");
        getContentPane().add(btn8);
        btn8.setBounds(100, 250, 60, 50);

        btnttk.setText(".");
        getContentPane().add(btnttk);
        btnttk.setBounds(170, 320, 60, 50);

        btnClr.setText("Clear");
        getContentPane().add(btnClr);
        btnClr.setBounds(30, 380, 410, 50);

        btnKurang.setText("-");
        getContentPane().add(btnKurang);
        btnKurang.setBounds(380, 320, 60, 50);

        btnKali.setText("x");
        getContentPane().add(btnKali);
        btnKali.setBounds(260, 130, 110, 50);

        btnBagi.setText("/");
        getContentPane().add(btnBagi);
        btnBagi.setBounds(260, 190, 110, 50);

        btnJumlah.setText("+");
        getContentPane().add(btnJumlah);
        btnJumlah.setBounds(260, 250, 110, 50);

        btn0.setText("0");
        getContentPane().add(btn0);
        btn0.setBounds(30, 320, 130, 50);

        btnsd.setText("=");
        getContentPane().add(btnsd);
        btnsd.setBounds(260, 320, 110, 50);

        btnPositifNegatif.setText("+/-");
        getContentPane().add(btnPositifNegatif);
        btnPositifNegatif.setBounds(380, 190, 60, 50);

        btnAkar.setText("√ ");
        getContentPane().add(btnAkar);
        btnAkar.setBounds(380, 130, 60, 50);

        btnkuadrat.setText("x^2");
        getContentPane().add(btnkuadrat);
        btnkuadrat.setBounds(380, 250, 60, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorStandart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAkar;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnJumlah;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnPositifNegatif;
    private javax.swing.JTextField btnTampil;
    private javax.swing.JButton btnkuadrat;
    private javax.swing.JButton btnsd;
    private javax.swing.JButton btnttk;
    // End of variables declaration//GEN-END:variables
}
