/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author Naufal K D
 */
public class Latihan01 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan01
     */
    public Latihan01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bilangan1 = new javax.swing.JTextField();
        Bilangan2 = new javax.swing.JTextField();
        ButtonKali = new javax.swing.JButton();
        ButtonJumlah = new javax.swing.JButton();
        BunttonKurang = new javax.swing.JButton();
        ButtonBagi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ravie", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 51));
        jLabel1.setText("Kalkulator Sederhana");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 10, 470, 50);

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 14)); // NOI18N
        jLabel2.setText("Bilangan1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 70, 70, 15);

        jLabel3.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 14)); // NOI18N
        jLabel3.setText("Bilangan2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 110, 70, 15);

        Bilangan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bilangan1ActionPerformed(evt);
            }
        });
        jPanel1.add(Bilangan1);
        Bilangan1.setBounds(180, 70, 170, 30);

        Bilangan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bilangan2ActionPerformed(evt);
            }
        });
        jPanel1.add(Bilangan2);
        Bilangan2.setBounds(180, 110, 170, 30);

        ButtonKali.setText("x");
        ButtonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKaliActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonKali);
        ButtonKali.setBounds(380, 160, 60, 60);

        ButtonJumlah.setText("+");
        ButtonJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJumlahActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonJumlah);
        ButtonJumlah.setBounds(140, 160, 60, 60);

        BunttonKurang.setText("-");
        BunttonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BunttonKurangActionPerformed(evt);
            }
        });
        jPanel1.add(BunttonKurang);
        BunttonKurang.setBounds(220, 160, 60, 60);

        ButtonBagi.setText("/");
        ButtonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBagiActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBagi);
        ButtonBagi.setBounds(300, 160, 60, 60);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Hasil");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 220, 80, 40);
        jPanel1.add(Hasil);
        Hasil.setBounds(160, 258, 280, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 400);

        setBounds(0, 0, 695, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void Bilangan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bilangan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bilangan1ActionPerformed

    private void Bilangan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bilangan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bilangan2ActionPerformed

    private void ButtonJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJumlahActionPerformed
        // TODO add your handling code here:
                double bil1 = Integer.parseInt(Bilangan1.getText());
        double bil2 = Integer.parseInt(Bilangan2.getText());
        double hasil = bil1+bil2;
        
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonJumlahActionPerformed

    private void BunttonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BunttonKurangActionPerformed
        // TODO add your handling code here:
                double bil1 = Integer.parseInt(Bilangan1.getText());
        double bil2 = Integer.parseInt(Bilangan2.getText());
        double hasil = bil1-bil2;
        
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_BunttonKurangActionPerformed

    private void ButtonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBagiActionPerformed
        // TODO add your handling code here:
                double bil1 = Integer.parseInt(Bilangan1.getText());
        double bil2 = Integer.parseInt(Bilangan2.getText());
        double hasil = bil1/bil2;
        
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonBagiActionPerformed

    private void ButtonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKaliActionPerformed
        // TODO add your handling code here:
                double bil1 = Integer.parseInt(Bilangan1.getText());
        double bil2 = Integer.parseInt(Bilangan2.getText());
        double hasil = bil1*bil2;
        
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonKaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bilangan1;
    private javax.swing.JTextField Bilangan2;
    private javax.swing.JButton BunttonKurang;
    private javax.swing.JButton ButtonBagi;
    private javax.swing.JButton ButtonJumlah;
    private javax.swing.JButton ButtonKali;
    private javax.swing.JTextField Hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
