/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author Naufal K D
 */
public class Latihan03 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan03
     */
    public Latihan03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrup = new javax.swing.ButtonGroup();
        judul = new javax.swing.JLabel();
        cm = new javax.swing.JLabel();
        saran = new javax.swing.JTextField();
        hasilBBideal = new javax.swing.JTextField();
        hasilnama = new javax.swing.JTextField();
        JKelamin = new javax.swing.JLabel();
        Hasil = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        TinggiBadan = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();
        Hitung = new javax.swing.JButton();
        Ulangi = new javax.swing.JButton();
        BeratBadan = new javax.swing.JLabel();
        kg = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        hasilTB = new javax.swing.JTextField();
        BBideal = new javax.swing.JLabel();
        HasilBB = new javax.swing.JTextField();
        analisa = new javax.swing.JTextField();
        SatuanHasil1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        judul.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("CEK KESEHATAN");
        getContentPane().add(judul);
        judul.setBounds(190, 30, 220, 32);

        cm.setText("Cm");
        getContentPane().add(cm);
        cm.setBounds(350, 150, 80, 30);

        saran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saranActionPerformed(evt);
            }
        });
        getContentPane().add(saran);
        saran.setBounds(110, 430, 390, 30);

        hasilBBideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilBBidealActionPerformed(evt);
            }
        });
        getContentPane().add(hasilBBideal);
        hasilBBideal.setBounds(260, 319, 60, 30);

        hasilnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilnamaActionPerformed(evt);
            }
        });
        getContentPane().add(hasilnama);
        hasilnama.setBounds(170, 70, 320, 30);

        JKelamin.setText("Jenis Kelamin");
        getContentPane().add(JKelamin);
        JKelamin.setBounds(80, 210, 80, 30);

        Hasil.setText("Hasil analisa kesehatan :");
        getContentPane().add(Hasil);
        Hasil.setBounds(90, 360, 190, 30);

        buttonGrup.add(rbLaki);
        rbLaki.setText("Laki - Laki");
        getContentPane().add(rbLaki);
        rbLaki.setBounds(170, 220, 73, 23);

        buttonGrup.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");
        rbPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanActionPerformed(evt);
            }
        });
        getContentPane().add(rbPerempuan);
        rbPerempuan.setBounds(350, 220, 79, 23);

        TinggiBadan.setText("Tinggi Badan");
        getContentPane().add(TinggiBadan);
        TinggiBadan.setBounds(80, 150, 80, 30);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(400, 260, 65, 25);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(80, 260, 64, 25);

        Ulangi.setText("Ulangi");
        Ulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlangiActionPerformed(evt);
            }
        });
        getContentPane().add(Ulangi);
        Ulangi.setBounds(240, 260, 63, 25);

        BeratBadan.setText("Berat Badan");
        getContentPane().add(BeratBadan);
        BeratBadan.setBounds(80, 110, 80, 30);

        kg.setText("Kg");
        getContentPane().add(kg);
        kg.setBounds(350, 110, 80, 30);

        Nama.setText("Nama");
        getContentPane().add(Nama);
        Nama.setBounds(80, 66, 50, 30);

        hasilTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilTBActionPerformed(evt);
            }
        });
        getContentPane().add(hasilTB);
        hasilTB.setBounds(170, 150, 170, 30);

        BBideal.setText("Berat badan ideal anda adalah :");
        getContentPane().add(BBideal);
        BBideal.setBounds(90, 320, 190, 30);

        HasilBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilBBActionPerformed(evt);
            }
        });
        getContentPane().add(HasilBB);
        HasilBB.setBounds(170, 110, 170, 30);

        analisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analisaActionPerformed(evt);
            }
        });
        getContentPane().add(analisa);
        analisa.setBounds(110, 390, 390, 30);

        SatuanHasil1.setText("Kg");
        getContentPane().add(SatuanHasil1);
        SatuanHasil1.setBounds(340, 320, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saranActionPerformed

    private void hasilBBidealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilBBidealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilBBidealActionPerformed

    private void hasilnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilnamaActionPerformed

    private void rbPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanActionPerformed

    private void hasilTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilTBActionPerformed

    private void HasilBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilBBActionPerformed

    private void analisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analisaActionPerformed

    private void UlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlangiActionPerformed
        // TODO add your handling code here:
        hasilnama.setText("");
        HasilBB.setText("");
        hasilBBideal.setText("");
        hasilTB.setText("");
        saran.setText("");
        analisa.setText("");
        rbPerempuan.setSelected(false);
        rbLaki.setSelected(false);
    }//GEN-LAST:event_UlangiActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        double t, b, h = 0;
        
        //untuk mengambil nilai tinggi dengan berat serta nama
        t = Double.valueOf(hasilTB.getText());
        b = Double.valueOf(HasilBB.getText());
        String nm = hasilnama.getText();
        
        //pilihan jenis kelamin
        if(rbLaki.isSelected())
        {
            h = (t-100);
        }
        else if(rbPerempuan.isSelected())
                {
                   h = (t-104); 
                }
        String temp = Double.toString(h);
        
        //logika untuk analisa hasil kesehatan
        if(h < b)
        {
            hasilBBideal.setText(temp);
            analisa.setText("Maaf "+nm+", Anda kelebihan berat badan");
            saran.setText("Atur pola makan mu dengan baik dan teratur");
        }
        else if(h>b)
        {
            hasilBBideal.setText(temp);
            analisa.setText("Maaf "+nm+", Anda kekurangan berat badan");
            saran.setText("Atur pola makan mu dan olahraga yang teratur");
        }
        else
        {
            hasilBBideal.setText(temp);
            analisa.setText("Hai "+nm+", Selamat! Berat badanmu Ideal");
            saran.setText("Tetap jaga pola makanmu dengan baik ya!");
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BBideal;
    private javax.swing.JLabel BeratBadan;
    private javax.swing.JLabel Hasil;
    private javax.swing.JTextField HasilBB;
    private javax.swing.JButton Hitung;
    private javax.swing.JLabel JKelamin;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel SatuanHasil1;
    private javax.swing.JLabel TinggiBadan;
    private javax.swing.JButton Ulangi;
    private javax.swing.JTextField analisa;
    private javax.swing.ButtonGroup buttonGrup;
    private javax.swing.JLabel cm;
    private javax.swing.JTextField hasilBBideal;
    private javax.swing.JTextField hasilTB;
    private javax.swing.JTextField hasilnama;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel kg;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField saran;
    // End of variables declaration//GEN-END:variables
}
