/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author Naufal K D
 */
public class Latihan02 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan02
     */
    public Latihan02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PilihanJurusan = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        VarAbsen = new javax.swing.JTextField();
        VarNama = new javax.swing.JTextField();
        rbdRPL = new javax.swing.JRadioButton();
        rbdTKJ = new javax.swing.JRadioButton();
        HobVideo = new javax.swing.JCheckBox();
        HobProgramming = new javax.swing.JCheckBox();
        HobAnimator = new javax.swing.JCheckBox();
        HobDesigner = new javax.swing.JCheckBox();
        Exit = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextHasil = new javax.swing.JTextArea();
        Hasil = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\Wallpaper\\lego_star_wars_stormtroopers-1280x720.jpg")); // NOI18N
        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 3, 24)); // NOI18N
        jLabel1.setText("BIODATA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 20, 170, 40);

        jLabel2.setText("Hobi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 180, 50, 30);

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 66, 50, 30);

        jLabel4.setText("Absen");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 100, 50, 30);

        jLabel5.setText("Jurusan");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 140, 50, 30);
        jPanel1.add(VarAbsen);
        VarAbsen.setBounds(170, 100, 320, 28);

        VarNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarNamaActionPerformed(evt);
            }
        });
        jPanel1.add(VarNama);
        VarNama.setBounds(170, 70, 320, 28);

        PilihanJurusan.add(rbdRPL);
        rbdRPL.setText("RPL");
        jPanel1.add(rbdRPL);
        rbdRPL.setBounds(320, 150, 50, 18);

        PilihanJurusan.add(rbdTKJ);
        rbdTKJ.setText("TKJ");
        rbdTKJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdTKJActionPerformed(evt);
            }
        });
        jPanel1.add(rbdTKJ);
        rbdTKJ.setBounds(170, 150, 43, 18);

        HobVideo.setText("VideoEditing");
        jPanel1.add(HobVideo);
        HobVideo.setBounds(310, 220, 120, 18);

        HobProgramming.setText("Programming");
        HobProgramming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HobProgrammingActionPerformed(evt);
            }
        });
        jPanel1.add(HobProgramming);
        HobProgramming.setBounds(170, 190, 100, 18);

        HobAnimator.setText("Animator");
        jPanel1.add(HobAnimator);
        HobAnimator.setBounds(310, 190, 71, 18);

        HobDesigner.setText("Designer");
        jPanel1.add(HobDesigner);
        HobDesigner.setBounds(170, 220, 73, 18);

        Exit.setText("Exit");
        jPanel1.add(Exit);
        Exit.setBounds(500, 250, 60, 28);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);
        Submit.setBounds(180, 250, 67, 28);

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        jPanel1.add(Remove);
        Remove.setBounds(340, 250, 90, 28);

        TextHasil.setColumns(20);
        TextHasil.setRows(5);
        jScrollPane1.setViewportView(TextHasil);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 350, 610, 270);

        Hasil.setFont(new java.awt.Font("Lucida Calligraphy", 3, 14)); // NOI18N
        Hasil.setText("Hasil");
        jPanel1.add(Hasil);
        Hasil.setBounds(360, 270, 210, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Wallpaper\\lego_star_wars_stormtroopers-1280x720.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 10, 860, 690);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 860, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        VarNama.setText("");
        VarAbsen.setText("");
        PilihanJurusan.clearSelection();
        TextHasil.setText("");
        HobProgramming.setSelected(false);
        HobDesigner.setSelected(false);
        HobAnimator.setSelected(false);
        HobVideo.setSelected(false);
    }//GEN-LAST:event_RemoveActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String nama = VarNama.getText();
        String absen = VarAbsen.getText();
        String jurusan;
        String hobi = "";
        
        //untuk pilihan jurusan
        if(rbdTKJ.isSelected())
            jurusan ="TKJ";
        else if(rbdRPL.isSelected())
            jurusan ="RPL";
        else
            jurusan = " ";
        
        //untuk pilihan checkbox
        if(HobProgramming.isSelected())
            hobi+=HobProgramming.getText()+",  ";
        if(HobDesigner.isSelected())
            hobi+=HobDesigner.getText()+",  ";
        if(HobAnimator.isSelected())
            hobi+=HobAnimator.getText()+",  ";
        if(HobVideo.isSelected())
            hobi+=HobVideo.getText()+",  ";
        
        //untuk hasil
        TextHasil.setText("Nama Anda : "+nama+"\nAbsen Anda : "+absen+"\nJurusan anda : "+jurusan+"\nHobi anda : "+hobi);
    }//GEN-LAST:event_SubmitActionPerformed

    private void VarNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VarNamaActionPerformed

    private void HobProgrammingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HobProgrammingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HobProgrammingActionPerformed

    private void rbdTKJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdTKJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbdTKJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Hasil;
    private javax.swing.JCheckBox HobAnimator;
    private javax.swing.JCheckBox HobDesigner;
    private javax.swing.JCheckBox HobProgramming;
    private javax.swing.JCheckBox HobVideo;
    private javax.swing.ButtonGroup PilihanJurusan;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Submit;
    private javax.swing.JTextArea TextHasil;
    private javax.swing.JTextField VarAbsen;
    private javax.swing.JTextField VarNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbdRPL;
    private javax.swing.JRadioButton rbdTKJ;
    // End of variables declaration//GEN-END:variables
}
